version: '3.9'

services:
  frontend:
    build: .
    ports:
      - "3002:3002"
    environment:
      - NODE_ENV=development
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev -- --port 3002 --host
