# ===============================================
# Frontend Docker Compose for React + Vite Application
# ===============================================

version: "3.8"

# Define network for service communication
networks:
  frontend_network:
    driver: bridge

# Define persistent volumes for data storage
volumes:
  # Nginx logs (optional - for log persistence)
  nginx_logs:
    driver: local

# Service definitions
services:
  # ================================
  # React Frontend Service
  # ================================
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      # Build arguments
      args:
        NODE_ENV: production
        VITE_API_URL: ${VITE_API_URL:-http://localhost:5000}

    container_name: pearson_frontend
    restart: unless-stopped

    # Environment variables for build
    environment:
      NODE_ENV: production
      VITE_API_URL: ${VITE_API_URL:-http://localhost:5000}

    # Port mapping - Frontend runs on port 3002
    ports:
      - "${FRONTEND_PORT:-3002}:3002"

    # Volume mapping for logs
    volumes:
      - nginx_logs:/var/log/nginx

    # Network configuration
    networks:
      - frontend_network

    # Health check for frontend readiness
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "wget --no-verbose --tries=1 --spider http://localhost:3002/health || exit 1",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
# ================================
# Development Override (Optional)
# ================================
# To use this compose file for development:
# docker-compose -f docker-compose.yml -f docker-compose.dev.yml up
